[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#6a006a"

[font]
size = 10

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.7

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
